// flash message
export const STORE_FLASH_MESSAGE = 'STORE_FLASH_MESSAGE'
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE'

// auth
export const STORE_AUTH_PROFILE = 'STORE_AUTH_PROFILE'
export const CLEAR_AUTH_PROFILE = 'CLEAR_AUTH_PROFILE'

// deposit filter
export const STORE_DEPOSIT_FILTER = 'STORE_DEPOSIT_FILTER'
export const CLEAR_DEPOSIT_FILTER = 'CLEAR_DEPOSIT_FILTER'

// project filter
export const STORE_PROJECT_FILTER = 'STORE_PROJECT_FILTER'
export const CLEAR_PROJECT_FILTER = 'CLEAR_PROJECT_FILTER'
