// flash message
export const STORE_FLASH_MESSAGE = 'STORE_FLASH_MESSAGE'
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE'

// auth
export const STORE_AUTH_PROFILE = 'STORE_AUTH_PROFILE'
export const CLEAR_AUTH_PROFILE = 'CLEAR_AUTH_PROFILE'

// deposit filter
export const STORE_DEPOSIT_FILTER = 'STORE_DEPOSIT_FILTER'
export const CLEAR_DEPOSIT_FILTER = 'CLEAR_DEPOSIT_FILTER'

// project filter
export const STORE_PROJECT_FILTER = 'STORE_PROJECT_FILTER'
export const CLEAR_PROJECT_FILTER = 'CLEAR_PROJECT_FILTER'

// header search
export const STORE_SEARCH_CURRENT_ROUTE = 'STORE_SEARCH_CURRENT_ROUTE'
export const STORE_SEARCH_SHOW_BADGE = 'STORE_SEARCH_SHOW_BADGE'
export const STORE_SEARCH_VISIBLE = 'STORE_SEARCH_VISIBLE'

// financing filter
export const STORE_FINANCING_FILTER = 'STORE_FINANCING_FILTER'
export const CLEAR_FINANCING_FILTER = 'CLEAR_FINANCING_FILTER'

// accounting filter
export const STORE_ACCOUNTING_FILTER = 'STORE_ACCOUNTING_FILTER'
export const CLEAR_ACCOUNTING_FILTER = 'CLEAR_ACCOUNTING_FILTER'

// dashboard
export const STORE_DASHBOARD_BLOCKS = 'STORE_DASHBOARD_BLOCKS'
export const CLEAR_DASHBOARD_BLOCKS = 'CLEAR_DASHBOARD_BLOCKS'

// account
export const STORE_ACCOUNT_PERMISSIONS = 'STORE_ACCOUNT_PERMISSIONS'
export const CLEAR_ACCOUNT_PERMISSIONS = 'CLEAR_ACCOUNT_PERMISSIONS'

// loading
export const STORE_FLASH_LOADING = 'STORE_FLASH_LOADING'

// jwt token
export const STORE_JWT_TOKEN = 'STORE_JWT_TOKEN'
