name: build frontend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Node Environment
        uses: actions/setup-node@v1
      - name: Install Packages and Build Application
        run: |
              npm ci
              npm run build
